"""Deterministic grounding validator verifying answer claims against retrieved evidence."""

import re
from typing import List, Set
from backend.app.generation.models import EvidenceContext, GroundingCheckResult

# Numerical values pattern (integers, decimals, and numbers with units)
NUMERIC_PATTERN = re.compile(r"\b\d+(?:\.\d+)?\b")

# Indian Standard identifier pattern
STANDARD_PATTERN = re.compile(r"\bIS\s+\d+(?:(?::\d{4})|(?:\s*:\s*\d{4}))?\b", re.IGNORECASE)

# Clause identifier pattern
CLAUSE_PATTERN = re.compile(r"\b(?:clause|cl\.?)\s+(\d+(?:\.\d+)*)\b|\bannex\s+([A-Z])\b", re.IGNORECASE)

# Mandatory prescriptive vocabulary
MANDATORY_TERMS = ["shall", "must", "mandatory", "required", "shall conform", "not less than", "not more than"]


class GroundingValidator:
    """Verifies factual claims, numerical bounds, and standard identifiers against source chunks."""

    @classmethod
    def check_grounding(
        cls,
        answer_text: str,
        context: EvidenceContext,
    ) -> GroundingCheckResult:
        """Execute deterministic grounding checks across answer text.
        
        Args:
            answer_text: The response narrative generated by the model.
            context: The authoritative EvidenceContext supplied.
            
        Returns:
            GroundingCheckResult with numerical, clause, standard, and score audits.
        """
        if not context.items:
            return GroundingCheckResult(
                grounding_score=0.0,
                is_grounded=False,
                violations=["No evidence available to ground the response."],
            )

        # Concatenate all authentic evidence content into an aggregate reference corpus
        corpus_text = " ".join([
            f"{item.standard_number or ''} {item.clause_number or ''} {item.content}"
            for item in context.items
        ])
        corpus_lower = corpus_text.lower()

        violations: List[str] = []
        supported_claims: List[str] = []
        unsupported_claims: List[str] = []

        # 1. Check Standard Numbers
        ans_standards = STANDARD_PATTERN.findall(answer_text)
        unsupported_standards = []
        for std in ans_standards:
            # Clean standard format
            std_clean = re.sub(r"\s+", " ", std).upper()
            if std_clean not in corpus_text.upper():
                unsupported_standards.append(std_clean)
                violations.append(f"Answer references ungrounded Indian Standard: '{std_clean}'.")

        # 2. Check Clause Numbers
        ans_clauses = CLAUSE_PATTERN.findall(answer_text)
        unsupported_clauses = []
        for c1, c2 in ans_clauses:
            target_cls = (c1 or c2).strip()
            # Ignore isolated single-digit numbers that could be bullet points (e.g. '1')
            if "." in target_cls or len(target_cls) > 1 or c2:
                if target_cls.lower() not in corpus_lower:
                    unsupported_clauses.append(target_cls)
                    violations.append(f"Answer references ungrounded clause identifier: '{target_cls}'.")

        # 3. Check Numerical Values
        ans_numbers = set(NUMERIC_PATTERN.findall(answer_text))
        corpus_numbers = set(NUMERIC_PATTERN.findall(corpus_text))

        # Filter out common punctuation, single digits (0, 1, 2), or common small values
        significant_ans_numbers = {n for n in ans_numbers if len(n) > 1 or float(n) > 3.0}
        unsupported_values = []
        for num in significant_ans_numbers:
            if num not in corpus_numbers:
                unsupported_values.append(num)
                violations.append(f"Answer contains ungrounded numerical value '{num}'.")

        # 4. Check Mandatory Prescriptive Language
        ans_lower = answer_text.lower()
        has_mandatory_in_ans = any(term in ans_lower for term in MANDATORY_TERMS)
        has_mandatory_in_corpus = any(term in corpus_lower for term in MANDATORY_TERMS)
        if has_mandatory_in_ans and not has_mandatory_in_corpus:
            violations.append("Answer introduces mandatory requirements ('shall'/'must') unsupported by evidence.")

        # 5. Compute Quantitative Grounding Score
        penalty = 0.0
        penalty += len(unsupported_standards) * 0.40
        penalty += len(unsupported_clauses) * 0.25
        penalty += len(unsupported_values) * 0.15
        if has_mandatory_in_ans and not has_mandatory_in_corpus:
            penalty += 0.20

        score = max(0.0, min(1.0, 1.0 - penalty))
        is_grounded = score >= 0.60 and len(unsupported_standards) == 0

        return GroundingCheckResult(
            grounding_score=round(score, 4),
            is_grounded=is_grounded,
            supported_claims=supported_claims,
            unsupported_claims=unsupported_claims,
            unsupported_values=unsupported_values,
            unsupported_clauses=unsupported_clauses,
            unsupported_standards=unsupported_standards,
            violations=violations,
        )
